services:
  poster:
    image: ghcr.io/psauxwwf/poster:latest
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - type=registry,ref=ghcr.io/psauxwwf/poster:latest
      cache_to:
        - type=inline
    container_name: poster
    volumes:
      - ~/.notebooklm:/root/.notebooklm
      - ./dist:/poster/dist
      - ./proxychains.conf:/usr/local/etc/proxychains.conf:ro
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_ADMIN_ID: ${TELEGRAM_ADMIN_ID}
      PROXYCHAINS: ${PROXYCHAINS}
    networks:
      - poster
    restart: unless-stopped
    stop_grace_period: 20s

networks:
  poster:
    name: poster
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 172.22.100.0/24
          gateway: 172.22.100.1
