services:
  poster:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/devil666face/poster:latest
    container_name: poster
    restart: unless-stopped
    stop_grace_period: 20s
    volumes:
      - ~/.notebooklm:/root/.notebooklm
      - ./dist:/poster/dist
    network_mode: "host"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_ADMIN_ID: ${TELEGRAM_ADMIN_ID}

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: "300"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_TRACE: "true"
      WATCHTOWER_REGISTRY_AUTH: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json:ro
    command: --debug poster
